FROM centos:7

RUN yum install -y --nogpgcheck tar centos-release-scl centos-release-scl-rh epel-release
RUN yum install -y --nogpgcheck scl-utils devtoolset-7 autoconf-archive cmake3 libcurl libcurl-devel openssl openssl-devel libuuid-devel hiredis hiredis-devel zlib zlib-devel libmemcached libmemcached-devel unixODBC* tar gzip wget nmap-ncat
RUN scl enable devtoolset-7 bash
RUN mv /usr/bin/cc /usr/bin/cc_old
RUN ln -s /opt/rh/devtoolset-7/root/usr/bin/gcc /usr/bin/cc
RUN ln -s /opt/rh/devtoolset-7/root/usr/bin/g++ /usr/bin/c++
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

#Install libcuckoo headers
WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
WORKDIR /tmp/libcuckoo-master
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ .
RUN make install
WORKDIR /tmp
RUN rm -rf /tmp/libcuckoo-master

#Install mongodb c driver
RUN wget -q https://github.com/mongodb/mongo-c-driver/releases/download/1.4.2/mongo-c-driver-1.4.2.tar.gz
RUN tar xf mongo-c-driver-1.4.2.tar.gz
RUN rm -f mongo-c-driver-1.4.2.tar.gz
RUN cd mongo-c-driver-1.4.2/ &&  ./configure --disable-automatic-init-and-cleanup --disable-tests --disable-ssl --disable-sasl && make && make install
WORKDIR /tmp
RUN rm -rf mongo-c-driver-1.4.2

#Install ffead-cpp
WORKDIR /tmp
RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip -qq master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip
WORKDIR /tmp/ffead-cpp-src
RUN cmake -DSRV_EMB=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on .
RUN make install -j4
RUN mv /tmp/ffead-cpp-src/ffead-cpp-4.0-bin /tmp/
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src

COPY *.sh  /opt/

WORKDIR /opt

RUN chmod +x install_ffead-cpp-4.0.sh
RUN ./install_ffead-cpp-4.0.sh

WORKDIR /opt/ffead-cpp-4.0

RUN chmod +x server.sh
CMD ./server.sh
