FROM archlinux/base

RUN pacman-key --init
RUN pacman-key --populate archlinux
RUN pacman -Sy archlinux-keyring pacman --noconfirm --noprogressbar --needed --quiet
RUN pacman-db-upgrade
RUN echo "[multilib]" >> /etc/pacman.conf \
    && echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf \
    && pacman -Sy --noprogressbar

RUN pacman -Su --noconfirm --noprogressbar --quiet
RUN pacman -Sy --noconfirm --noprogressbar autoconf-archive make clang make git binutils patch base-devel wget

COPY yay-aur.sh /
RUN chmod +x /yay-aur.sh
RUN /yay-aur.sh

RUN pacman -Syyu --noconfirm

#Add martchus.no-ip.biz repo for mingw binaries
RUN echo "[ownstuff]" >> /etc/pacman.conf \
    && echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf \
    && echo "Server = https://martchus.no-ip.biz/repo/arch/\$repo/os/\$arch " >> /etc/pacman.conf \
    && pacman -Sy

RUN pacman -S --noconfirm --noprogressbar mingw-w64-gcc mingw-w64-make mingw-w64-configure \
	mingw-w64-pkg-config mingw-w64-curl mingw-w64-openssl mingw-w64-zlib mingw-w64-jsoncpp \
	mingw-w64-crt mingw-w64-headers mingw-w64-readline mingw-w64-cmake unzip

RUN wget -q http://www.unixodbc.org/unixODBC-2.3.7.tar.gz
RUN tar zxvf unixODBC-2.3.7.tar.gz
WORKDIR unixODBC-2.3.7
RUN ./configure --host=x86_64-w64-mingw32
RUN make
RUN make install

#Install libcuckoo headers
WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip master.zip
RUN rm -f master.zip

RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip

WORKDIR /tmp/libcuckoo-master
RUN x86_64-w64-mingw32-cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ .
RUN make install
WORKDIR /tmp
RUN rm -rf /tmp/libcuckoo-master

RUN pacman -S --noconfirm --noprogressbar mingw-w64-libsystre

#Install ffead-cpp
WORKDIR /tmp/ffead-cpp-src
RUN cmake -DCMAKE_TOOLCHAIN_FILE=mingw-64-toolchain.cmake -DSRV_EMB=on .
RUN make install -j4
RUN mv /tmp/ffead-cpp-src/ffead-cpp-4.0-bin /tmp/
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src

WORKDIR /opt

COPY *.sh  ./

RUN chmod +x install_ffead-cpp-4.0.sh
RUN ./install_ffead-cpp-4.0.sh

WORKDIR /opt/ffead-cpp-4.0

RUN chmod +x server.sh
CMD ./server.sh
