FROM opensuse/leap

RUN zypper in -y autoconf-archive autoconf automake procps libtool perl gcc gcc-c++ make cmake postgresql-devel libcurl-devel openssl openssl-devel libmemcached-devel zlib-devel libuuid-devel unixODBC unixODBC-devel unzip wget netcat-openbsd tar gzip

#Install libcuckoo headers
WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
WORKDIR /tmp/libcuckoo-master
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ .
RUN make install
WORKDIR /tmp
RUN rm -rf /tmp/libcuckoo-master

RUN wget -q https://github.com/redis/hiredis/archive/v1.0.0.tar.gz
RUN tar xf v1.0.0.tar.gz
RUN rm -f v1.0.0.tar.gz
RUN cd hiredis-1.0.0/ && cmake . && make install
WORKDIR /tmp
RUN rm -rf hiredis-1.0.0

RUN wget -q https://github.com/sewenew/redis-plus-plus/archive/refs/tags/1.3.10.tar.gz
RUN tar xf 1.3.10.tar.gz
RUN rm -f 1.3.10.tar.gz
WORKDIR redis-plus-plus-1.3.10/
RUN mkdir build
WORKDIR build
RUN cmake -DREDIS_PLUS_PLUS_CXX_STANDARD=17 .. && make && make install
WORKDIR /tmp
RUN rm -rf redis-plus-plus-1.3.10

#Install mongodb c driver
ENV VERSION=1.26.2
RUN wget "https://github.com/mongodb/mongo-c-driver/archive/refs/tags/$VERSION.tar.gz" --output-document="mongo-c-driver-$VERSION.tar.gz"
RUN tar xf "mongo-c-driver-$VERSION.tar.gz"
RUN rm -f "mongo-c-driver-$VERSION.tar.gz"
RUN cd mongo-c-driver-$VERSION/ && mkdir _build && cmake -S . -B _build \
-D ENABLE_EXTRA_ALIGNMENT=OFF \
-D ENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -D ENABLE_TESTS=OFF -D ENABLE_EXAMPLES=OFF \
-D CMAKE_BUILD_TYPE=RelWithDebInfo \
-D BUILD_VERSION="$VERSION" \
-D ENABLE_SSL=OFF \
-D ENABLE_SASL=OFF \
-D ENABLE_MONGOC=ON && cmake --build _build --config RelWithDebInfo --parallel && cmake --install _build
RUN rm -rf "mongo-c-driver-$VERSION"

#Install ffead-cpp
WORKDIR /tmp
RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip -qq master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip
WORKDIR /tmp/ffead-cpp-src
RUN chmod +x autogen.sh
RUN sed -i 's|AC_CHECK_LIB(pq, PQenterPipelineMode|#AC_CHECK_LIB(pq, PQenterPipelineMode|g' configure.ac
RUN ./autogen.sh
RUN ./configure --enable-srv_emb=yes --enable-mod_sdormmongo=yes --enable-mod_rediscache=yes --enable-mod_memcached=yes
RUN make install
RUN mv /tmp/ffead-cpp-src/ffead-cpp-7.0-bin /tmp/
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src

COPY *.sh  /opt/

WORKDIR /opt

RUN echo "/usr/local/lib64" >> /etc/ld.so.conf && ldconfig
RUN chmod +x install_ffead-cpp.sh
RUN ./install_ffead-cpp.sh

WORKDIR /opt/ffead-cpp-7.0

RUN chmod +x server.sh
CMD ./server.sh
