FROM ubuntu:latest

ENV DEBIAN_FRONTEND noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt update -yqq && apt install -yqq gcc g++ software-properties-common cmake unzip libpcre3-dev zlib1g-dev libpq-dev \
	libssl-dev uuid-dev odbc-postgresql unixodbc unixodbc-dev libcurl4-openssl-dev libmemcached-dev wget netcat \
	rapidjson-dev libpugixml-dev zstd clang lldb lld && rm -rf /var/lib/apt/lists/*
#RUN wget -q https://github.com/sumeetchhetri/shellb/releases/download/2.0.0/shellb -P /usr/local/bin && chmod +x /usr/local/bin/shellb 
RUN wget -q https://github.com/facebook/buck2/releases/download/latest/buck2-x86_64-unknown-linux-gnu.zst && unzstd buck2-x86_64-unknown-linux-gnu.zst \
	&& mv buck2-x86_64-unknown-linux-gnu /usr/local/bin/buck2 && chmod +x /usr/local/bin/buck2

#Install libcuckoo headers
WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
WORKDIR /tmp/libcuckoo-master
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ .
RUN make install
WORKDIR /tmp
RUN rm -rf /tmp/libcuckoo-master

RUN wget -q https://github.com/redis/hiredis/archive/v1.0.0.tar.gz
RUN tar xf v1.0.0.tar.gz
RUN rm -f v1.0.0.tar.gz
RUN cd hiredis-1.0.0/ && cmake . && make install
WORKDIR /tmp
RUN rm -rf hiredis-1.0.0

RUN wget -q https://github.com/sewenew/redis-plus-plus/archive/refs/tags/1.3.3.tar.gz
RUN tar xf 1.3.3.tar.gz
RUN rm -f 1.3.3.tar.gz
WORKDIR redis-plus-plus-1.3.3/
RUN mkdir build
WORKDIR build
RUN cmake -DREDIS_PLUS_PLUS_CXX_STANDARD=17 .. && make && make install
WORKDIR /tmp
RUN rm -rf redis-plus-plus-1.3.3

#Install mongodb c driver
RUN wget -q https://github.com/mongodb/mongo-c-driver/releases/download/1.4.2/mongo-c-driver-1.4.2.tar.gz
RUN tar xf mongo-c-driver-1.4.2.tar.gz
RUN rm -f mongo-c-driver-1.4.2.tar.gz
RUN cd mongo-c-driver-1.4.2/ &&  ./configure --disable-automatic-init-and-cleanup --disable-tests --disable-ssl --disable-sasl && make && make install
WORKDIR /tmp
RUN rm -rf mongo-c-driver-1.4.2

#Install ffead-cpp
WORKDIR /tmp
RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip -qq master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip
WORKDIR /tmp/ffead-cpp-src

#RUN rm -f /usr/local/bin/shellb && wget -q https://github.com/sumeetchhetri/shellb/releases/download/2.0.0/shellb -P /usr/local/bin && chmod +x /usr/local/bin/shellb

RUN chmod +x ./shellb && ./shellb ffead-cpp-buck2
RUN mv /tmp/ffead-cpp-src/shellb_out/ffead-cpp-6.0-bin /tmp/
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src

COPY *.sh  /opt/

WORKDIR /opt

RUN chmod +x install_ffead-cpp.sh
RUN ./install_ffead-cpp.sh
