FROM alpine:latest

RUN apk add autoconf-archive autoconf automake libtool gcc g++ make cmake unzip postgresql-dev openssl openssl-dev psqlodbc unixodbc unixodbc-dev curl-dev libmemcached libmemcached-dev wget netcat-openbsd bash
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing ossp-uuid-dev

#Install libcuckoo headers
WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
WORKDIR /tmp/libcuckoo-master
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ .
RUN make install
WORKDIR /tmp
RUN rm -rf /tmp/libcuckoo-master

#Install mongodb c driver
RUN wget -q https://github.com/mongodb/mongo-c-driver/releases/download/1.4.2/mongo-c-driver-1.4.2.tar.gz
RUN tar xf mongo-c-driver-1.4.2.tar.gz
RUN rm -f mongo-c-driver-1.4.2.tar.gz
RUN cd mongo-c-driver-1.4.2/ &&  ./configure --disable-automatic-init-and-cleanup &&  make && make install
WORKDIR /tmp
RUN rm -rf mongo-c-driver-1.4.2

RUN wget -q https://github.com/redis/hiredis/archive/v1.0.0.tar.gz
RUN tar xf v1.0.0.tar.gz
RUN rm -f v1.0.0.tar.gz
RUN cd hiredis-1.0.0/ && cmake . && make install
WORKDIR /tmp
RUN rm -rf hiredis-1.0.0

RUN wget -q https://github.com/sewenew/redis-plus-plus/archive/refs/tags/1.3.10.tar.gz
RUN tar xf 1.3.10.tar.gz
RUN rm -f 1.3.10.tar.gz
WORKDIR redis-plus-plus-1.3.10/
RUN mkdir build
WORKDIR build
RUN cmake -DREDIS_PLUS_PLUS_CXX_STANDARD=17 .. && make && make install
WORKDIR /tmp
RUN rm -rf redis-plus-plus-1.3.10

#Install ffead-cpp
WORKDIR /tmp
RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip -qq master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip
WORKDIR /tmp/ffead-cpp-src
RUN chmod +x autogen.sh
RUN ./autogen.sh
RUN ./configure LDFLAGS="-Wl,-z,stack-size=2097152" --enable-srv_emb=yes --enable-mod_sdormmongo=yes --enable-mod_sdormsql=yes --enable-mod_rediscache=yes --enable-mod_memcached=yes
RUN make install
RUN mv /tmp/ffead-cpp-src/ffead-cpp-7.0-bin /tmp/
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src

COPY *.sh  /opt/

WORKDIR /opt

RUN chmod +x install_ffead-cpp.sh
RUN ./install_ffead-cpp.sh

WORKDIR /opt/ffead-cpp-7.0

RUN chmod +x server.sh
CMD ./server.sh
