# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :solaris114
  config.vm.box = "FEBO/solaris-11.4"
  config.vm.box_check_update = false
  #config.vm.network "forwarded_port", guest: 8080, host: 8002
  #config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.box_download_insecure = true
  # Set freebsd shell
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"

  # config.vm.network "public_network", type: "dhcp"
  config.vm.network "private_network", type: "dhcp"

  #config.vm.synced_folder ".", "/vagrant", :nfs => true, id: "vagrant-root",
  #:mount_options => ['rw', 'vers=3', 'tcp', 'actimeo=2']

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    # vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    # vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
