################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/Constants.cpp \
../src/ServiceTask.cpp \
../src/SSLHandler.cpp \
../src/ConfigurationHandler.cpp \
../src/ConfigurationData.cpp \
../src/ExtHandler.cpp \
../src/FviewHandler.cpp \
../src/ScriptHandler.cpp \
../src/SoapHandler.cpp \
../src/FormHandler.cpp \
../src/ControllerHandler.cpp \
../src/AuthHandler.cpp \
../src/FilterHandler.cpp \
../src/SecurityHandler.cpp \
../src/AOPEngine.cpp \
../src/AfcUtil.cpp \
../src/AppContext.cpp \
../src/ApplicationUtil.cpp \
../src/Aspect.cpp \
../src/BeanContext.cpp \
../src/BinaryData.cpp \
../src/Block.cpp \
../src/Cache.cpp \
../src/CfusionEngine.cpp \
../src/Cibernate.cpp \
../src/CibernateConnPools.cpp \
../src/CibernateConnectionPool.cpp \
../src/Class.cpp \
../src/ClassInfo.cpp \
../src/Client.cpp \
../src/Component.cpp \
../src/ComponentGen.cpp \
../src/ComponentHandler.cpp \
../src/ConnectionSettings.cpp \
../src/Constructor.cpp \
../src/CppInterpreter.cpp \
../src/DCPGenerator.cpp \
../src/Date.cpp \
../src/DateFormat.cpp \
../src/Destination.cpp \
../src/Document.cpp \
../src/DynamicView.cpp \
../src/Element.cpp \
../src/Exception.cpp \
../src/ExceptionHandler.cpp \
../src/FFEADContext.cpp \
../src/Field.cpp \
../src/HttpRequest.cpp \
../src/HttpResponse.cpp \
../src/HttpSession.cpp \
../src/IMAPHandler.cpp \
../src/InvalidMessageException.cpp \
../src/Logger.cpp \
../src/Message.cpp \
../src/MessageHandler.cpp \
../src/MessageUtil.cpp \
../src/Method.cpp \
../src/MethodInvoc.cpp \
../src/PropFileReader.cpp \
../src/Queue.cpp \
../src/Reflection.cpp \
../src/Reflector.cpp \
../src/RemoteComponent.cpp \
../src/Renderer.cpp \
../src/SOAPRequest.cpp \
../src/SOAPResponse.cpp \
../src/SOAPUtil.cpp \
../src/Serialize.cpp \
../src/Server.cpp \
../src/Service.cpp \
../src/ServiceInt.cpp \
../src/ServicePool.cpp \
../src/Task.cpp \
../src/TaskPool.cpp \
../src/TemplateEngine.cpp \
../src/TemplateHandler.cpp \
../src/Thread.cpp \
../src/ThreadPool.cpp \
../src/Timer.cpp \
../src/Trace.cpp \
../src/View.cpp \
../src/WsUtil.cpp \
../src/XmlParseException.cpp \
../src/XmlParser.cpp \
../src/json_spirit_reader.cpp \
../src/json_spirit_value.cpp \
../src/json_spirit_writer.cpp \
../src/AuthController.cpp \
../src/FileAuthController.cpp \
../src/DBAuthController.cpp \
../src/LDAPAuthController.cpp \
../src/CryptoHandler.cpp \
../src/HttpResponseParser.cpp \
../src/SSLClient.cpp \
../src/RestController.cpp \
../src/Filter.cpp

OBJS += \
./src/Constants.o \
./src/ServiceTask.o \
./src/SSLHandler.o \
./src/ConfigurationHandler.o \
./src/ConfigurationData.o \
./src/ExtHandler.o \
./src/FviewHandler.o \
./src/ScriptHandler.o \
./src/SoapHandler.o \
./src/FormHandler.o \
./src/ControllerHandler.o \
./src/AuthHandler.o \
./src/FilterHandler.o \
./src/SecurityHandler.o \
./src/AOPEngine.o \
./src/AfcUtil.o \
./src/AppContext.o \
./src/ApplicationUtil.o \
./src/Aspect.o \
./src/BeanContext.o \
./src/BinaryData.o \
./src/Block.o \
./src/Cache.o \
./src/CfusionEngine.o \
./src/Cibernate.o \
./src/CibernateConnPools.o \
./src/CibernateConnectionPool.o \
./src/Class.o \
./src/ClassInfo.o \
./src/Client.o \
./src/Component.o \
./src/ComponentGen.o \
./src/ComponentHandler.o \
./src/ConnectionSettings.o \
./src/Constructor.o \
./src/CppInterpreter.o \
./src/DCPGenerator.o \
./src/Date.o \
./src/DateFormat.o \
./src/Destination.o \
./src/Document.o \
./src/DynamicView.o \
./src/Element.o \
./src/Exception.o \
./src/ExceptionHandler.o \
./src/FFEADContext.o \
./src/Field.o \
./src/HttpRequest.o \
./src/HttpResponse.o \
./src/HttpSession.o \
./src/IMAPHandler.o \
./src/InvalidMessageException.o \
./src/Logger.o \
./src/Message.o \
./src/MessageHandler.o \
./src/MessageUtil.o \
./src/Method.o \
./src/MethodInvoc.o \
./src/PropFileReader.o \
./src/Queue.o \
./src/Reflection.o \
./src/Reflector.o \
./src/RemoteComponent.o \
./src/Renderer.o \
./src/SOAPRequest.o \
./src/SOAPResponse.o \
./src/SOAPUtil.o \
./src/Serialize.o \
./src/Server.o \
./src/Service.o \
./src/ServiceInt.o \
./src/ServicePool.o \
./src/Task.o \
./src/TaskPool.o \
./src/TemplateEngine.o \
./src/TemplateHandler.o \
./src/Thread.o \
./src/ThreadPool.o \
./src/Timer.o \
./src/Trace.o \
./src/View.o \
./src/WsUtil.o \
./src/XmlParseException.o \
./src/XmlParser.o \
./src/json_spirit_reader.o \
./src/json_spirit_value.o \
./src/json_spirit_writer.o \
./src/AuthController.o \
./src/FileAuthController.o \
./src/DBAuthController.o \
./src/LDAPAuthController.o \
./src/CryptoHandler.o \
./src/HttpResponseParser.o \
./src/SSLClient.o \
./src/RestController.o \
./src/Filter.o

CPP_DEPS += \
./src/Constants.d \
./src/ServiceTask.d \
./src/SSLHandler.d \
./src/ConfigurationHandler.d \
./src/ConfigurationData.d \
./src/ExtHandler.d \
./src/FviewHandler.d \
./src/ScriptHandler.d \
./src/SoapHandler.d \
./src/FormHandler.d \
./src/ControllerHandler.d \
./src/AuthHandler.d \
./src/FilterHandler.d \
./src/SecurityHandler.d \
./src/AOPEngine.d \
./src/AfcUtil.d \
./src/AppContext.d \
./src/ApplicationUtil.d \
./src/Aspect.d \
./src/BeanContext.d \
./src/BinaryData.d \
./src/Block.d \
./src/Cache.d \
./src/CfusionEngine.d \
./src/Cibernate.d \
./src/CibernateConnPools.d \
./src/CibernateConnectionPool.d \
./src/Class.d \
./src/ClassInfo.d \
./src/Client.d \
./src/Component.d \
./src/ComponentGen.d \
./src/ComponentHandler.d \
./src/ConnectionSettings.d \
./src/Constructor.d \
./src/CppInterpreter.d \
./src/DCPGenerator.d \
./src/Date.d \
./src/DateFormat.d \
./src/Destination.d \
./src/Document.d \
./src/DynamicView.d \
./src/Element.d \
./src/Exception.d \
./src/ExceptionHandler.d \
./src/FFEADContext.d \
./src/Field.d \
./src/HttpRequest.d \
./src/HttpResponse.d \
./src/HttpSession.d \
./src/IMAPHandler.d \
./src/InvalidMessageException.d \
./src/Logger.d \
./src/Message.d \
./src/MessageHandler.d \
./src/MessageUtil.d \
./src/Method.d \
./src/MethodInvoc.d \
./src/PropFileReader.d \
./src/Queue.d \
./src/Reflection.d \
./src/Reflector.d \
./src/RemoteComponent.d \
./src/Renderer.d \
./src/SOAPRequest.d \
./src/SOAPResponse.d \
./src/SOAPUtil.d \
./src/Serialize.d \
./src/Server.d \
./src/Service.d \
./src/ServiceInt.d \
./src/ServicePool.d \
./src/Task.d \
./src/TaskPool.d \
./src/TemplateEngine.d \
./src/TemplateHandler.d \
./src/Thread.d \
./src/ThreadPool.d \
./src/Timer.d \
./src/Trace.d \
./src/View.d \
./src/WsUtil.d \
./src/XmlParseException.d \
./src/XmlParser.d \
./src/json_spirit_reader.d \
./src/json_spirit_value.d \
./src/json_spirit_writer.d \
./src/AuthController.d \
./src/FileAuthController.d \
./src/DBAuthController.d \
./src/LDAPAuthController.d \
./src/CryptoHandler.d \
./src/HttpResponseParser.d \
./src/SSLClient.d \
./src/RestController.d \
./src/Filter.d


# Each subdirectory must supply rules for building sources it contributes
%.o: ../../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -l ../src/ -I../include -O0 -Wall -g3 -c -fmessage-length=0 -fPIC -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


