FROM archlinux:latest

#RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
#    curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && \
#    bsdtar -C / -xvf "$patched_glibc"
#RUN echo "IgnorePkg   = glibc" >> /etc/pacman.conf

RUN pacman-key --init
RUN pacman -Sy --noconfirm --noprogressbar gawk
RUN pacman-key --populate archlinux
RUN pacman -Sy archlinux-keyring pacman --noconfirm --noprogressbar --needed --quiet
RUN pacman-db-upgrade
RUN echo "[multilib]" >> /etc/pacman.conf \
    && echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf \
	&& echo "[ownstuff]" >> /etc/pacman.conf \
    && echo "Server = https://martchus.no-ip.biz/repo/arch/\$repo/os/\$arch " >> /etc/pacman.conf
RUN sed -i 's|SigLevel    = Required DatabaseOptional|SigLevel    = Never|g' /etc/pacman.conf && pacman -Sy --noprogressbar

RUN pacman -S --noconfirm --noprogressbar gcc gcc-libs glibc libtool mingw-w64-gcc mingw-w64-make mingw-w64-configure \
	mingw-w64-pkg-config mingw-w64-curl mingw-w64-openssl mingw-w64-zlib mingw-w64-jsoncpp \
	mingw-w64-crt mingw-w64-headers mingw-w64-readline mingw-w64-cmake mingw-w64-dlfcn \
	unzip wget tar grep sed make core/binutils diffutils base-devel

ENV TARGET=x86_64-w64-mingw32

WORKDIR /tmp
RUN wget -q https://ftp.osuosl.org/pub/blfs/conglomeration/unixODBC/unixODBC-2.3.7.tar.gz
RUN tar zxvf unixODBC-2.3.7.tar.gz
RUN rm -f unixODBC-2.3.7.tar.gz
WORKDIR unixODBC-2.3.7
RUN env NM=${TARGET}-nm AS=${TARGET}-as LD=${TARGET}-ld CC=${TARGET}-gcc AR=${TARGET}-ar \
	RANLIB=${TARGET}-ranlib CFLAGS="-D_FORTIFY_SOURCE=2" LDFLAGS="-lssp" ./configure --host=${TARGET} --prefix=/usr/${TARGET}
RUN ${TARGET}-make
RUN ${TARGET}-make install
WORKDIR /tmp
RUN rm -rf unixODBC-2.3.7

RUN wget -q https://github.com/sean-/ossp-uuid/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
WORKDIR ossp-uuid-master
RUN env NM=${TARGET}-nm AS=${TARGET}-as LD=${TARGET}-ld CC=${TARGET}-gcc AR=${TARGET}-ar \
	RANLIB=${TARGET}-ranlib CFLAGS="-D_FORTIFY_SOURCE=2" LDFLAGS="-lssp" ./configure --prefix=/usr/${TARGET} \
	--without-pgsql --without-perl --without-php --disable-static \
	--host=x86_64 ac_cv_va_copy=C99 --enable-shared && ${TARGET}-make
RUN mv uuid.exe uuid
RUN cp /usr/sbin/${TARGET}-strip /usr/sbin/strip
RUN ${TARGET}-make install
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid.po uuid.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_cli.po uuid_cli.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_dce.po uuid_dce.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_mac.po uuid_mac.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_md5.po uuid_md5.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_prng.po uuid_prng.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_sha1.po uuid_sha1.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_str.po uuid_str.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_time.po uuid_time.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_ui128.po uuid_ui128.c
RUN ${TARGET}-gcc -D_FORTIFY_SOURCE=2 -c -fPIC -o uuid_ui64.po uuid_ui64.c
RUN ${TARGET}-gcc -shared -fPIC -Wl,-soname,libossp-uuid.dll -lssp -o libossp-uuid.dll *.po
RUN cp libossp-uuid.dll /usr/${TARGET}/lib/
RUN cp /usr/${TARGET}/lib/libuuid.a /usr/${TARGET}/lib/libossp-uuid.dll.a
WORKDIR /tmp
RUN rm -rf ossp-uuid-master

WORKDIR /tmp
RUN wget -q https://github.com/efficient/libcuckoo/archive/master.zip
RUN unzip -qq master.zip
RUN rm -f master.zip
RUN cd libcuckoo-master && ${TARGET}-cmake -DCMAKE_INSTALL_PREFIX=/usr/${TARGET} . && ${TARGET}-make install
WORKDIR /tmp
RUN rm -rf libcuckoo-master

RUN cd /tmp && wget -q https://github.com/kkos/oniguruma/releases/download/v6.9.6/onig-6.9.6.tar.gz && tar xf onig-6.9.6.tar.gz && \
	cd onig-6.9.6 && ${TARGET}-cmake -DENABLE_BINARY_COMPATIBLE_POSIX_API=on . && ${TARGET}-make -j4 install

WORKDIR /tmp
RUN wget -q https://github.com/redis/hiredis/archive/8e0264cfd6889b73c241b60736fe96ba1322ee6e.zip
RUN unzip -qq 8e0264cfd6889b73c241b60736fe96ba1322ee6e.zip
RUN rm -f 8e0264cfd6889b73c241b60736fe96ba1322ee6e.zip
WORKDIR hiredis-8e0264cfd6889b73c241b60736fe96ba1322ee6e
RUN ${TARGET}-cmake . && ${TARGET}-make install
WORKDIR /tmp
RUN rm -rf hiredis-8e0264cfd6889b73c241b60736fe96ba1322ee6e

RUN wget -q https://github.com/mongodb/mongo-c-driver/releases/download/1.4.2/mongo-c-driver-1.4.2.tar.gz
RUN tar xf mongo-c-driver-1.4.2.tar.gz
RUN rm -f mongo-c-driver-1.4.2.tar.gz
WORKDIR mongo-c-driver-1.4.2
RUN env NM=${TARGET}-nm AS=${TARGET}-as LD=${TARGET}-ld CC=${TARGET}-gcc AR=${TARGET}-ar \
	RANLIB=${TARGET}-ranlib CFLAGS="-D__USE_MINGW_ANSI_STDIO=1 -D_FORTIFY_SOURCE=2" LDFLAGS="-lssp" \
	./configure --disable-automatic-init-and-cleanup --disable-tests --disable-ssl --disable-sasl \
	--prefix=/usr/${TARGET} --host=${TARGET} && CFLAGS="-D__USE_MINGW_ANSI_STDIO=1" LDFLAGS="-lssp" \
	${TARGET}-make && ${TARGET}-make install -j4
WORKDIR /tmp
RUN rm -rf mongo-c-driver-1.4.2
RUN rm -f /usr/${TARGET}/include/libbson-1.0/bson-compat.h
RUN wget -q https://raw.githubusercontent.com/mongodb/mongo-c-driver/f5eb70637fdd391fe14c9a9f3ec3cfda193f3ad9/src/libbson/src/bson/bson-compat.h
RUN mv bson-compat.h /usr/${TARGET}/include/libbson-1.0/
RUN wget -q https://raw.githubusercontent.com/mongodb/mongo-c-driver/f5eb70637fdd391fe14c9a9f3ec3cfda193f3ad9/src/libbson/src/bson/bson-prelude.h
RUN mv bson-prelude.h /usr/${TARGET}/include/libbson-1.0/

RUN wget -q https://github.com/sumeetchhetri/ffead-cpp/archive/master.zip
RUN unzip -qq master.zip
RUN mv ffead-cpp-master ffead-cpp-src
RUN rm -f master.zip
WORKDIR /tmp/ffead-cpp-src
RUN mkdir build
WORKDIR /tmp/ffead-cpp-src/build
RUN CC=${TARGET}-gcc CXX=${TARGET}-g++ ${TARGET}-cmake -DSRV_EMB=ON -DMOD_SDORM_MONGO=ON -DMOD_REDIS=on -DCMAKE_INC_PATH=/usr/${TARGET} ..
RUN ${TARGET}-make install -j4
RUN mv /tmp/ffead-cpp-src/ffead-cpp-6.0-bin /opt/
#WORKDIR /tmp/ffead-cpp-src
#RUN chmod +x autogen.sh
#RUN sed -i'' -e "s|m4_include|#m4_include|g" configure.ac
#RUN sed -i'' -e "s|AX_CXX_COMPILE_STDCXX|#AX_CXX_COMPILE_STDCXX|g" configure.ac
#RUN sed -i'' -e "s|AC_CHECK_LIB(regex|#AC_CHECK_LIB(regex|g" configure.ac
#RUN ./autogen.sh
#RUN env NM=${TARGET}-nm AS=${TARGET}-as LD=${TARGET}-ld CC=${TARGET}-gcc CXX=${TARGET}-g++ AR=${TARGET}-ar RANLIB=${TARGET}-ranlib C_INCLUDE_PATH=${STAGE_DIR}/include \
#	CPPFLAGS="-I/usr/${TARGET}/include -std=c++17" LDFLAGS="-L/usr/${TARGET}/lib -fstack-protector" ./configure --host="${TARGET}" --enable-srv_emb=yes --enable-mod_sdormmongo=yes \
#	--enable-mod_sdormsql=yes --enable-mod_rediscache=yes --with-top_inc_dir=/usr/${TARGET}/include
#RUN make install -j4
#RUN mv /tmp/ffead-cpp-src/ffead-cpp-6.0-bin /opt/ffead-cpp-6.0-bin_ac
WORKDIR /tmp
RUN rm -rf /tmp/ffead-cpp-src
