fasthttp-ffead-cpp: clean
	go mod download
	go build -ldflags="-s -w" -o fasthttp-ffead-cpp .

#fasthttp-ffead-cpp: clean
#	go get -u github.com/valyala/fasthttp
#	go get -u github.com/valyala/fasthttp/prefork
#	go build -ldflags="-s -w" -o fasthttp-ffead-cpp .

clean:
	rm -f fasthttp-ffead-cpp