<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="${WS_NAME}ImplService" targetNamespace="http://webservice.bd/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://webservice.bd/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:types>
		<xsd:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://webservice.bd" xmlns:tns="http://webservice.bd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			${OBJ_BINDING}    
		</xsd:schema>
		<xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://webservice.bd/" xmlns:ns0="http://webservice.bd" xmlns:tns="http://webservice.bd/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://webservice.bd" />
			${REQ_RES_BINDING}
		</xsd:schema>
	</wsdl:types>
	${WSDL_MESSAGES}
	<wsdl:portType name="${WS_NAME}">
		${WSDL_OPERATIONS}
	</wsdl:portType>
	<wsdl:binding name="${WS_NAME}ImplServiceSoapBinding" type="tns:${WS_NAME}">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		${WSDL_BINDING}
	</wsdl:binding>
	<wsdl:service name="${WS_NAME}ImplService">
		<wsdl:port binding="tns:${WS_NAME}ImplServiceSoapBinding" name="${WS_NAME}ImplPort">
		<soap:address location="${URL}/${WS_NAME}" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
